name: marketplacedb
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.1.0
  intl:
  carousel_slider: ^4.2.1
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  permission_handler: ^10.0.1
  google_sign_in: ^6.1.5
  another_flushbar: ^1.12.30
  flutter_facebook_auth: ^6.0.2
  dio: ^5.3.3
  url_launcher: ^6.2.1
  flutter_screenutil: ^5.9.0
  intl_phone_field: ^3.2.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  image_path: "flutter_images/mp.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  #-----------------------LOCAL ASSETS-----------------------#
  assets:
    - assets/images/
    - assets/images/promotion_banners/
    - assets/fonts/
    - assets/animations/

  #-----------------------LOCAL FONTS-----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
